[ -f pact/ffi/linuxx8664/libpact_ffi.so  ] && echo "done"
# [ -f pacts/Consumer-Alice Service.json  ] && echo "done"
# [ -f pacts/http-consumer-2-http-provider.json ] && echo "done"
# [ -f pacts/message-consumer-2-message-provider.json  ] && echo "done"
# [ -f pacts/http-consumer-1-http-provider.json  ] && echo "done"
